sudo: required
services:
    - docker

before_install:
    - docker build -t jahirbnavaz/docker-goggles -f Dockerfile.dev .

script:
    - docker run -e CI=true jahirbnavaz/docker-goggles npm run test
